# Generated by Django 5.1.4 on 2024-12-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('country', 'year', 'month', 'name')},
            },
        ),
    ]
